// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PositionsController from "./positions_controller.js"
import StakingController from "./staking_controller.js"

application.register("positions", PositionsController)
application.register("staking", StakingController)
