AAVEETH: [AAVE, ETH]
ADAETH: [ADA, ETH]
ADXETH: [ADX, ETH]
AEETH: [AE, ETH]
AGIETH: [AGI, ETH]
AIONETH: [AION, ETH]
AMBETH: [AMB, ETH]
APEETH: [APE, ETH]
APPCETH: [APPC, ETH]
ARDRETH: [ARDR, ETH]
ARKETH: [ARK, ETH]
ARNETH: [ARN, ETH]
ASTETH: [AST, ETH]
ASTRETH: [ASTR, ETH]
ATOMETH: [ATOM, ETH]
AVAXETH: [AVAX, ETH]
AXSETH: [AXS, ETH]
BATETH: [BAT, ETH]
BCCETH: [BCC, ETH]
BCDETH: [BCD, ETH]
BCNETH: [BCN, ETH]
BCPTETH: [BCPT, ETH]
BETAETH: [BETA, ETH]
BETHETH: [BETH, ETH]
BLZETH: [BLZ, ETH]
BNBETH: [BNB, ETH]
BNTETH: [BNT, ETH]
BQXETH: [BQX, ETH]
BRDETH: [BRD, ETH]
BSWETH: [BSW, ETH]
BTGETH: [BTG, ETH]
BTSETH: [BTS, ETH]
CDTETH: [CDT, ETH]
CELRETH: [CELR, ETH]
CHATETH: [CHAT, ETH]
CHRETH: [CHR, ETH]
CLOAKETH: [CLOAK, ETH]
CMTETH: [CMT, ETH]
CNDETH: [CND, ETH]
COVERETH: [COVER, ETH]
CRVETH: [CRV, ETH]
CVCETH: [CVC, ETH]
CVPETH: [CVP, ETH]
DASHETH: [DASH, ETH]
DATAETH: [DATA, ETH]
DENTETH: [DENT, ETH]
DEXEETH: [DEXE, ETH]
DFETH: [DF, ETH]
DGDETH: [DGD, ETH]
DLTETH: [DLT, ETH]
DNTETH: [DNT, ETH]
DOCKETH: [DOCK, ETH]
DOTETH: [DOT, ETH]
DYDXETH: [DYDX, ETH]
EASYETH: [EASY, ETH]
EDOETH: [EDO, ETH]
EGLDETH: [EGLD, ETH]
ELFETH: [ELF, ETH]
ENGETH: [ENG, ETH]
ENJETH: [ENJ, ETH]
EOSETH: [EOS, ETH]
ETCETH: [ETC, ETH]
EVXETH: [EVX, ETH]
EZETH: [EZ, ETH]
FARMETH: [FARM, ETH]
FIROETH: [FIRO, ETH]
FRONTETH: [FRONT, ETH]
FTMETH: [FTM, ETH]
FTTETH: [FTT, ETH]
FUELETH: [FUEL, ETH]
FUNETH: [FUN, ETH]
GALAETH: [GALA, ETH]
GHSTETH: [GHST, ETH]
GLMETH: [GLM, ETH]
GMTETH: [GMT, ETH]
GNTETH: [GNT, ETH]
GRSETH: [GRS, ETH]
GRTETH: [GRT, ETH]
GTOETH: [GTO, ETH]
GVTETH: [GVT, ETH]
GXSETH: [GXS, ETH]
HCETH: [HC, ETH]
HEGICETH: [HEGIC, ETH]
HOTETH: [HOT, ETH]
HSRETH: [HSR, ETH]
ICNETH: [ICN, ETH]
ICPETH: [ICP, ETH]
ICXETH: [ICX, ETH]
INSETH: [INS, ETH]
IOSTETH: [IOST, ETH]
IOTAETH: [IOTA, ETH]
IOTXETH: [IOTX, ETH]
JASMYETH: [JASMY, ETH]
KAVAETH: [KAVA, ETH]
KEYETH: [KEY, ETH]
KMDETH: [KMD, ETH]
KNCETH: [KNC, ETH]
KSMETH: [KSM, ETH]
LENDETH: [LEND, ETH]
LINKETH: [LINK, ETH]
LOOMETH: [LOOM, ETH]
LRCETH: [LRC, ETH]
LSKETH: [LSK, ETH]
LTCETH: [LTC, ETH]
LUNAETH: [LUNA, ETH]
LUNETH: [LUN, ETH]
MANAETH: [MANA, ETH]
MATICETH: [MATIC, ETH]
MCOETH: [MCO, ETH]
MDAETH: [MDA, ETH]
MFTETH: [MFT, ETH]
MODETH: [MOD, ETH]
MTHETH: [MTH, ETH]
MTLETH: [MTL, ETH]
NANOETH: [NANO, ETH]
NASETH: [NAS, ETH]
NAVETH: [NAV, ETH]
NCASHETH: [NCASH, ETH]
NEARETH: [NEAR, ETH]
NEOETH: [NEO, ETH]
NPXSETH: [NPXS, ETH]
NULSETH: [NULS, ETH]
NXSETH: [NXS, ETH]
OAXETH: [OAX, ETH]
OMGETH: [OMG, ETH]
ONEETH: [ONE, ETH]
ONTETH: [ONT, ETH]
OOKIETH: [OOKI, ETH]
OSTETH: [OST, ETH]
PAXETH: [PAX, ETH]
PHXETH: [PHX, ETH]
POAETH: [POA, ETH]
POEETH: [POE, ETH]
POWRETH: [POWR, ETH]
PPTETH: [PPT, ETH]
PROSETH: [PROS, ETH]
PUNDIXETH: [PUNDIX, ETH]
QKCETH: [QKC, ETH]
QLCETH: [QLC, ETH]
QSPETH: [QSP, ETH]
QTUMETH: [QTUM, ETH]
RCNETH: [RCN, ETH]
RDNETH: [RDN, ETH]
RENBTCETH: [RENBTC, ETH]
REQETH: [REQ, ETH]
RLCETH: [RLC, ETH]
ROSEETH: [ROSE, ETH]
RPXETH: [RPX, ETH]
RUNEETH: [RUNE, ETH]
SALTETH: [SALT, ETH]
SANDETH: [SAND, ETH]
SCETH: [SC, ETH]
SCRTETH: [SCRT, ETH]
SKYETH: [SKY, ETH]
SLPETH: [SLP, ETH]
SNGLSETH: [SNGLS, ETH]
SNMETH: [SNM, ETH]
SNTETH: [SNT, ETH]
SOLETH: [SOL, ETH]
SSVETH: [SSV, ETH]
STEEMETH: [STEEM, ETH]
STMXETH: [STMX, ETH]
STORJETH: [STORJ, ETH]
STORMETH: [STORM, ETH]
STRATETH: [STRAT, ETH]
STRAXETH: [STRAX, ETH]
SUBETH: [SUB, ETH]
SUSDETH: [SUSD, ETH]
SYSETH: [SYS, ETH]
THETAETH: [THETA, ETH]
TNBETH: [TNB, ETH]
TNTETH: [TNT, ETH]
TRIGETH: [TRIG, ETH]
TRXETH: [TRX, ETH]
TUSDETH: [TUSD, ETH]
UFTETH: [UFT, ETH]
UNIETH: [UNI, ETH]
VENETH: [VEN, ETH]
VETETH: [VET, ETH]
VGXETH: [VGX, ETH]
VIAETH: [VIA, ETH]
VIBEETH: [VIBE, ETH]
VIBETH: [VIB, ETH]
VOXELETH: [VOXEL, ETH]
WABIETH: [WABI, ETH]
WANETH: [WAN, ETH]
WAVESETH: [WAVES, ETH]
WBTCETH: [WBTC, ETH]
WINGSETH: [WINGS, ETH]
WPRETH: [WPR, ETH]
WTCETH: [WTC, ETH]
XEMETH: [XEM, ETH]
XLMETH: [XLM, ETH]
XMRETH: [XMR, ETH]
XNOETH: [XNO, ETH]
XRPETH: [XRP, ETH]
XTZETH: [XTZ, ETH]
XVGETH: [XVG, ETH]
XZCETH: [XZC, ETH]
YOYOETH: [YOYO, ETH]
ZECETH: [ZEC, ETH]
ZENETH: [ZEN, ETH]
ZILETH: [ZIL, ETH]
ZRXETH: [ZRX, ETH]
