# Australian Dollar
AUD:
  ADAAUD: [ADA, AUD]
  APEAUD: [APE, AUD]
  AVAXAUD: [AVAX, AUD]
  AXSAUD: [AXS, AUD]
  BNBAUD: [BNB, AUD]
  BTCAUD: [BTC, AUD]
  CAKEAUD: [CAKE, AUD]
  DOGEAUD: [DOGE, AUD]
  DOTAUD: [DOT, AUD]
  EOSAUD: [EOS, AUD]
  ETHAUD: [ETH, AUD]
  FTMAUD: [FTM, AUD]
  GALAAUD: [GALA, AUD]
  KSMAUD: [KSM, AUD]
  LINKAUD: [LINK, AUD]
  LUNAAUD: [LUNA, AUD]
  MATICAUD: [MATIC, AUD]
  NUAUD: [NU, AUD]
  RUNEAUD: [RUNE, AUD]
  SANDAUD: [SAND, AUD]
  SHIBAUD: [SHIB, AUD]
  SOLAUD: [SOL, AUD]
  SXPAUD: [SXP, AUD]
  TRXAUD: [TRX, AUD]
  UNIAUD: [UNI, AUD]
  XRPAUD: [XRP, AUD]

BKRW:
  AAVEBKRW: [AAVE, BKRW]
  ADABKRW: [ADA, BKRW]
  BNBBKRW: [BNB, BKRW]
  BTCBKRW: [BTC, BKRW]
  BUSDBKRW: [BUSD, BKRW]
  DOTBKRW: [DOT, BKRW]
  ETHBKRW: [ETH, BKRW]
  LENDBKRW: [LEND, BKRW]
  LINKBKRW: [LINK, BKRW]
  USDTBKRW: [USDT, BKRW]
  XRPBKRW: [XRP, BKRW]

BRL:
  AAVEBRL: [AAVE, BRL]
  ADABRL: [ADA, BRL]
  ATOMBRL: [ATOM, BRL]
  AVAXBRL: [AVAX, BRL]
  AXSBRL: [AXS, BRL]
  BNBBRL: [BNB, BRL]
  BTCBRL: [BTC, BRL]
  BTTBRL: [BTT, BRL]
  BUSDBRL: [BUSD, BRL]
  C98BRL: [C98, BRL]
  CAKEBRL: [CAKE, BRL]
  CHZBRL: [CHZ, BRL]
  DOGEBRL: [DOGE, BRL]
  DOTBRL: [DOT, BRL]
  ENJBRL: [ENJ, BRL]
  ETCBRL: [ETC, BRL]
  ETHBRL: [ETH, BRL]
  FISBRL: [FIS, BRL]
  FTMBRL: [FTM, BRL]
  GALABRL: [GALA, BRL]
  GMTBRL: [GMT, BRL]
  HOTBRL: [HOT, BRL]
  LINKBRL: [LINK, BRL]
  LTCBRL: [LTC, BRL]
  LUNABRL: [LUNA, BRL]
  MANABRL: [MANA, BRL]
  MATICBRL: [MATIC, BRL]
  SANDBRL: [SAND, BRL]
  SANTOSBRL: [SANTOS, BRL]
  SHIBBRL: [SHIB, BRL]
  SOLBRL: [SOL, BRL]
  USDTBRL: [USDT, BRL]
  WINBRL: [WIN, BRL]
  XRPBRL: [XRP, BRL]

BVND:
  BUSDBVND: [BUSD, BVND]
  USDTBVND: [USDT, BVND]

BIDR:
  ADABIDR: [ADA, BIDR]
  ALGOBIDR: [ALGO, BIDR]
  ALICEBIDR: [ALICE, BIDR]
  ATOMBIDR: [ATOM, BIDR]
  AVAXBIDR: [AVAX, BIDR]
  AXSBIDR: [AXS, BIDR]
  BNBBIDR: [BNB, BIDR]
  BTCBIDR: [BTC, BIDR]
  BUSDBIDR: [BUSD, BIDR]
  DOGEBIDR: [DOGE, BIDR]
  DOTBIDR: [DOT, BIDR]
  ETHBIDR: [ETH, BIDR]
  FISBIDR: [FIS, BIDR]
  FTMBIDR: [FTM, BIDR]
  LUNABIDR: [LUNA, BIDR]
  MANABIDR: [MANA, BIDR]
  MATICBIDR: [MATIC, BIDR]
  NBTBIDR: [NBT, BIDR]
  ONEBIDR: [ONE, BIDR]
  REEFBIDR: [REEF, BIDR]
  SANDBIDR: [SAND, BIDR]
  SLPBIDR: [SLP, BIDR]
  SOLBIDR: [SOL, BIDR]
  SRMBIDR: [SRM, BIDR]
  SXPBIDR: [SXP, BIDR]
  TKOBIDR: [TKO, BIDR]
  USDTBIDR: [USDT, BIDR]
  XRPBIDR: [XRP, BIDR]
  ZILBIDR: [ZIL, BIDR]

DAI:
  BNBDAI: [BNB, DAI]
  BTCDAI: [BTC, DAI]
  BUSDDAI: [BUSD, DAI]
  ETHDAI: [ETH, DAI]
  USDTDAI: [USDT, DAI]

DOGE:
  SHIBDOGE: [SHIB, DOGE]

DOT:
  BDOTDOT: [BDOT, DOT]

# Euro
EUR:
  ADAEUR: [ADA, EUR]
  ALPINEEUR: [ALPINE, EUR]
  APEEUR: [APE, EUR]
  ATOMEUR: [ATOM, EUR]
  AVAXEUR: [AVAX, EUR]
  BCHEUR: [BCH, EUR]
  BNBEUR: [BNB, EUR]
  BTCEUR: [BTC, EUR]
  BTTEUR: [BTT, EUR]
  CHZEUR: [CHZ, EUR]
  DAREUR: [DAR, EUR]
  DOGEEUR: [DOGE, EUR]
  DOTEUR: [DOT, EUR]
  EGLDEUR: [EGLD, EUR]
  ENJEUR: [ENJ, EUR]
  EOSEUR: [EOS, EUR]
  ETCEUR: [ETC, EUR]
  ETHEUR: [ETH, EUR]
  FTMEUR: [FTM, EUR]
  GALAEUR: [GALA, EUR]
  GALEUR: [GAL, EUR]
  GMTEUR: [GMT, EUR]
  GRTEUR: [GRT, EUR]
  HOTEUR: [HOT, EUR]
  ICPEUR: [ICP, EUR]
  JASMYEUR: [JASMY, EUR]
  LAZIOEUR: [LAZIO, EUR]
  LINKEUR: [LINK, EUR]
  LTCEUR: [LTC, EUR]
  LUNAEUR: [LUNA, EUR]
  MATICEUR: [MATIC, EUR]
  NEAREUR: [NEAR, EUR]
  OPEUR: [OP, EUR]
  PORTOEUR: [PORTO, EUR]
  RUNEEUR: [RUNE, EUR]
  SHIBEUR: [SHIB, EUR]
  SOLEUR: [SOL, EUR]
  SXPEUR: [SXP, EUR]
  THETAEUR: [THETA, EUR]
  TRXEUR: [TRX, EUR]
  UNIEUR: [UNI, EUR]
  VETEUR: [VET, EUR]
  WAVESEUR: [WAVES, EUR]
  WINEUR: [WIN, EUR]
  WRXEUR: [WRX, EUR]
  XLMEUR: [XLM, EUR]
  XRPEUR: [XRP, EUR]
  YFIEUR: [YFI, EUR]
  ZILEUR: [ZIL, EUR]

# British Pound
GBP:
  ADAGBP: [ADA, GBP]
  APEGBP: [APE, GBP]
  AVAXGBP: [AVAX, GBP]
  BNBGBP: [BNB, GBP]
  BTCGBP: [BTC, GBP]
  CAKEGBP: [CAKE, GBP]
  CHZGBP: [CHZ, GBP]
  DOGEGBP: [DOGE, GBP]
  DOTGBP: [DOT, GBP]
  ENJGBP: [ENJ, GBP]
  ETCGBP: [ETC, GBP]
  ETHGBP: [ETH, GBP]
  GMTGBP: [GMT, GBP]
  LINKGBP: [LINK, GBP]
  LTCGBP: [LTC, GBP]
  LUNAGBP: [LUNA, GBP]
  MATICGBP: [MATIC, GBP]
  RUNEGBP: [RUNE, GBP]
  SHIBGBP: [SHIB, GBP]
  SOLGBP: [SOL, GBP]
  SXPGBP: [SXP, GBP]
  VETGBP: [VET, GBP]
  XRPGBP: [XRP, GBP]

IDRT:
  BNBIDRT: [BNB, IDRT]
  BTCIDRT: [BTC, IDRT]
  BUSDIDRT: [BUSD, IDRT]
  USDTIDRT: [USDT, IDRT]

NGN:
  BNBNGN: [BNB, NGN]
  BTCNGN: [BTC, NGN]
  BUSDNGN: [BUSD, NGN]
  DOTNGN: [DOT, NGN]
  ETHNGN: [ETH, NGN]
  LINKNGN: [LINK, NGN]
  LTCNGN: [LTC, NGN]
  TRXNGN: [TRX, NGN]
  USDTNGN: [USDT, NGN]
  XRPNGN: [XRP, NGN]

PAX:
  ADAPAX: [ADA, PAX]
  ALGOPAX: [ALGO, PAX]
  ANKRPAX: [ANKR, PAX]
  ATOMPAX: [ATOM, PAX]
  BATPAX: [BAT, PAX]
  BCHABCPAX: [BCHABC, PAX]
  BCHPAX: [BCH, PAX]
  BCHSVPAX: [BCHSV, PAX]
  BCPTPAX: [BCPT, PAX]
  BNBPAX: [BNB, PAX]
  BTCPAX: [BTC, PAX]
  BTTPAX: [BTT, PAX]
  DOGEPAX: [DOGE, PAX]
  DUSKPAX: [DUSK, PAX]
  EOSPAX: [EOS, PAX]
  ERDPAX: [ERD, PAX]
  ETCPAX: [ETC, PAX]
  ETHPAX: [ETH, PAX]
  FTMPAX: [FTM, PAX]
  GTOPAX: [GTO, PAX]
  LINKPAX: [LINK, PAX]
  LTCPAX: [LTC, PAX]
  NEOPAX: [NEO, PAX]
  ONEPAX: [ONE, PAX]
  ONTPAX: [ONT, PAX]
  PHBPAX: [PHB, PAX]
  TFUELPAX: [TFUEL, PAX]
  TRXPAX: [TRX, PAX]
  USDCPAX: [USDC, PAX]
  USDSPAX: [USDS, PAX]
  WAVESPAX: [WAVES, PAX]
  XLMPAX: [XLM, PAX]
  XRPPAX: [XRP, PAX]
  ZECPAX: [ZEC, PAX]

# Russian Ruble
RUB:
  ADARUB: [ADA, RUB]
  ALGORUB: [ALGO, RUB]
  ARPARUB: [ARPA, RUB]
  BNBRUB: [BNB, RUB]
  BTCRUB: [BTC, RUB]
  BUSDRUB: [BUSD, RUB]
  DOGERUB: [DOGE, RUB]
  DOTRUB: [DOT, RUB]
  ETHRUB: [ETH, RUB]
  FTMRUB: [FTM, RUB]
  ICPRUB: [ICP, RUB]
  LTCRUB: [LTC, RUB]
  MATICRUB: [MATIC, RUB]
  NEARRUB: [NEAR, RUB]
  NEORUB: [NEO, RUB]
  NURUB: [NU, RUB]
  SHIBRUB: [SHIB, RUB]
  SOLRUB: [SOL, RUB]
  TRURUB: [TRU, RUB]
  USDTRUB: [USDT, RUB]
  WAVESRUB: [WAVES, RUB]
  XRPRUB: [XRP, RUB]

TRX:
  BTTTRX: [BTT, TRX]
  WINTRX: [WIN, TRX]

TRY:
  ADATRY: [ADA, TRY]
  ALGOTRY: [ALGO, TRY]
  ALICETRY: [ALICE, TRY]
  ALPINETRY: [ALPINE, TRY]
  APETRY: [APE, TRY]
  API3TRY: [API3, TRY]
  ARPATRY: [ARPA, TRY]
  ATOMTRY: [ATOM, TRY]
  AUDIOTRY: [AUDIO, TRY]
  AVAXTRY: [AVAX, TRY]
  AXSTRY: [AXS, TRY]
  BELTRY: [BEL, TRY]
  BNBTRY: [BNB, TRY]
  BSWTRY: [BSW, TRY]
  BTCTRY: [BTC, TRY]
  BTTCTRY: [BTTC, TRY]
  BTTTRY: [BTT, TRY]
  BUSDTRY: [BUSD, TRY]
  CHZTRY: [CHZ, TRY]
  COCOSTRY: [COCOS, TRY]
  COSTRY: [COS, TRY]
  DARTRY: [DAR, TRY]
  DENTTRY: [DENT, TRY]
  DOGETRY: [DOGE, TRY]
  DOTTRY: [DOT, TRY]
  ENJTRY: [ENJ, TRY]
  ENSTRY: [ENS, TRY]
  EOSTRY: [EOS, TRY]
  ETHTRY: [ETH, TRY]
  FILTRY: [FIL, TRY]
  FISTRY: [FIS, TRY]
  FTMTRY: [FTM, TRY]
  GALATRY: [GALA, TRY]
  GALTRY: [GAL, TRY]
  GMTTRY: [GMT, TRY]
  GRTTRY: [GRT, TRY]
  HOTTRY: [HOT, TRY]
  ICPTRY: [ICP, TRY]
  INJTRY: [INJ, TRY]
  JASMYTRY: [JASMY, TRY]
  LAZIOTRY: [LAZIO, TRY]
  LINKTRY: [LINK, TRY]
  LRCTRY: [LRC, TRY]
  LUNATRY: [LUNA, TRY]
  MANATRY: [MANA, TRY]
  MATICTRY: [MATIC, TRY]
  MBOXTRY: [MBOX, TRY]
  MINATRY: [MINA, TRY]
  NEARTRY: [NEAR, TRY]
  NEOTRY: [NEO, TRY]
  ONETRY: [ONE, TRY]
  ONTTRY: [ONT, TRY]
  PORTOTRY: [PORTO, TRY]
  REEFTRY: [REEF, TRY]
  ROSETRY: [ROSE, TRY]
  RUNETRY: [RUNE, TRY]
  RVNTRY: [RVN, TRY]
  SANDTRY: [SAND, TRY]
  SANTOSTRY: [SANTOS, TRY]
  SHIBTRY: [SHIB, TRY]
  SLPTRY: [SLP, TRY]
  SOLTRY: [SOL, TRY]
  SPELLTRY: [SPELL, TRY]
  SXPTRY: [SXP, TRY]
  TLMTRY: [TLM, TRY]
  TRXTRY: [TRX, TRY]
  TWTTRY: [TWT, TRY]
  UMATRY: [UMA, TRY]
  USDTTRY: [USDT, TRY]
  VETTRY: [VET, TRY]
  WAVESTRY: [WAVES, TRY]
  XLMTRY: [XLM, TRY]
  XRPTRY: [XRP, TRY]
  XTZTRY: [XTZ, TRY]
  ZILTRY: [ZIL, TRY]

TUSD:
  ADATUSD: [ADA, TUSD]
  ALGOTUSD: [ALGO, TUSD]
  ANKRTUSD: [ANKR, TUSD]
  ATOMTUSD: [ATOM, TUSD]
  BATTUSD: [BAT, TUSD]
  BCHABCTUSD: [BCHABC, TUSD]
  BCHSVTUSD: [BCHSV, TUSD]
  BCHTUSD: [BCH, TUSD]
  BCPTTUSD: [BCPT, TUSD]
  BNBTUSD: [BNB, TUSD]
  BTCTUSD: [BTC, TUSD]
  BTTTUSD: [BTT, TUSD]
  EOSTUSD: [EOS, TUSD]
  ETCTUSD: [ETC, TUSD]
  ETHTUSD: [ETH, TUSD]
  FTMTUSD: [FTM, TUSD]
  GTOTUSD: [GTO, TUSD]
  LINKTUSD: [LINK, TUSD]
  LTCTUSD: [LTC, TUSD]
  NEOTUSD: [NEO, TUSD]
  ONETUSD: [ONE, TUSD]
  PAXTUSD: [PAX, TUSD]
  PHBTUSD: [PHB, TUSD]
  TFUELTUSD: [TFUEL, TUSD]
  TRXTUSD: [TRX, TUSD]
  TUSDBTUSD: [TUSDB, TUSD]
  USDCTUSD: [USDC, TUSD]
  USDSTUSD: [USDS, TUSD]
  WAVESTUSD: [WAVES, TUSD]
  XLMTUSD: [XLM, TUSD]
  XRPTUSD: [XRP, TUSD]
  ZECTUSD: [ZEC, TUSD]

UAH:
  BNBUAH: [BNB, UAH]
  BTCUAH: [BTC, UAH]
  BUSDUAH: [BUSD, UAH]
  ETHUAH: [ETH, UAH]
  LTCUAH: [LTC, UAH]
  SHIBUAH: [SHIB, UAH]
  USDTUAH: [USDT, UAH]

USDP:
  BNBUSDP: [BNB, USDP]
  BTCUSDP: [BTC, USDP]
  ETHUSDP: [ETH, USDP]

USDS:
  BNBUSDS: [BNB, USDS]
  BTCUSDS: [BTC, USDS]
  USDSBUSDS: [USDSB, USDS]

UST:
  BNBUST: [BNB, UST]
  BTCUST: [BTC, UST]
  ETHUST: [ETH, UST]
  LUNAUST: [LUNA, UST]

VAI:
  BTCVAI: [BTC, VAI]
  BUSDVAI: [BUSD, VAI]

XRP:
  TRXXRP: [TRX, XRP]
  XZCXRP: [XZC, XRP]

ZAR:
  BNBZAR: [BNB, ZAR]
  BTCZAR: [BTC, ZAR]
  BUSDZAR: [BUSD, ZAR]
  ETHZAR: [ETH, ZAR]
  USDTZAR: [USDT, ZAR]
