ADAUSDC: [ADA, USDC]
ALGOUSDC: [ALGO, USDC]
ANKRUSDC: [ANKR, USDC]
ATOMUSDC: [ATOM, USDC]
AUDUSDC: [AUD, USDC]
BATUSDC: [BAT, USDC]
BCHABCUSDC: [BCHABC, USDC]
BCHSVUSDC: [BCHSV, USDC]
BCHUSDC: [BCH, USDC]
BCPTUSDC: [BCPT, USDC]
BGBPUSDC: [BGBP, USDC]
BNBUSDC: [BNB, USDC]
BTCUSDC: [BTC, USDC]
BTTCUSDC: [BTTC, USDC]
BTTUSDC: [BTT, USDC]
DOGEUSDC: [DOGE, USDC]
DUSKUSDC: [DUSK, USDC]
EOSUSDC: [EOS, USDC]
ERDUSDC: [ERD, USDC]
ETCUSDC: [ETC, USDC]
ETHUSDC: [ETH, USDC]
FTMUSDC: [FTM, USDC]
GTOUSDC: [GTO, USDC]
LINKUSDC: [LINK, USDC]
LTCUSDC: [LTC, USDC]
NEOUSDC: [NEO, USDC]
NPXSUSDC: [NPXS, USDC]
ONEUSDC: [ONE, USDC]
ONTUSDC: [ONT, USDC]
PERLUSDC: [PERL, USDC]
PHBUSDC: [PHB, USDC]
SOLUSDC: [SOL, USDC]
TFUELUSDC: [TFUEL, USDC]
TOMOUSDC: [TOMO, USDC]
TRXUSDC: [TRX, USDC]
USDSUSDC: [USDS, USDC]
WAVESUSDC: [WAVES, USDC]
WINUSDC: [WIN, USDC]
XLMUSDC: [XLM, USDC]
XRPUSDC: [XRP, USDC]
ZECUSDC: [ZEC, USDC]
