name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: postgres:13
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - name: Install gems
        run: bundle install

      - name: Setup Database
        env:
          GITHUB: true
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: rails db:create db:schema:load

      - name: Run tests with rspec
        env:
          GITHUB: true
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
        run: bundle exec rspec

  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1

      - run: bundle install

      # Add or Replace any other security checks here
      # - name: Run security checks
      #   run: |
      #     bin/bundler-audit --update
      #     bin/brakeman -q -w2

      # Add or Replace any other Linters here
      - name: Run linters
        run: rubocop
